### PR TITLE
Command set versionning (fix #34)

### LINKED ISSUE #30: Dependency Tracking
please add your dependencies as git submodules to track the version. (this includes the packager)

### LINKED ISSUE #34: Bootloader Command Set Version
Add a version number for command set.

### PR DESCRIPTION
**Pull request by antoinealb**
first pull request of the year \o/

This implements command set versionning. I am not entierly sure of my implementation details, especially for the tests, so peer review welcomed.

### CODE REVIEW

**Comment by msplr** [comment]
Why don't you use the `COMMAND_SET_VERSION` macro/variable for all tests? Isn't it cumbersome to change all tests for every version change?
The rest looks good to me.

**Comment by antoinealb** [comment]
Well it would change the CRC, so you would have to repair the tests either way. Although the best is probably to compute the CRC automatically.

**Comment by msplr** [comment]
We should probably add compatibility tests between python and C implementations.
Now we only test each part with itself, which isn't always correct for the actual application.

**Comment by antoinealb** [comment]
I was thinking about it too, but I don't know if it is worth it. I would do it by making a C to Python binding to the target code and then write all compatibility tests in python.

**Comment by msplr** [comment]
opened an issue #41 to discuss this topic.

**Comment by antoinealb** [comment]
It should not be a problem as `cmp_read_int` handles both signed and unsigned integers (see https://github.com/camgunz/cmp/blob/master/cmp.c#L1202-L1235). I can change it though.

**Comment by msplr** [comment]
I think this can merge.

**Pull request merged**
