### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by antoinealb**
This patchset fixes the unit test build and also adds a few tests for the jump command.

I think we should really try to keep those tests working, because having a reliable build on Linux will allow us to use advanced quality tools such as static analyzers, etc. I can play QA guy and add those tests after each pull request, but it would be easier for everyone if those who write the code also write the tests during development.

### CODE REVIEW

**Comment by msplr** [comment]
I fixed some unit tests - it should pass now.
You can merge from: https://github.com/nuft/can-bootloader/tree/fix-unit-tests

**Comment by antoinealb** [comment]
I added your changes. I don't know why, but Clang is ok, where GCC is not: https://travis-ci.org/antoinealb/can-bootloader/builds/44931851

@nuft Do you know what might cause this problem ? Apparently the problematic line is:

``` c
command_t commands[] = {
        {.index = 0x00, .callback = mock_command},
    };
```

**Comment by Stapelzeiger** [comment]
Maybe the `,` at the end of line 2.

**Comment by antoinealb** [comment]
I wasn't able to reproduce on my local GCC (4.9). Apparently tagged struct
init are not valid c++ so I removed them (see commits). Now all tests are
passing and Travis ci is watching so for me it is ready for merge.

**Pull request merged**
