### PR TITLE
Read flash command.

### PR DESCRIPTION
**Pull request by msplr**
Minimal implementation for a flash read command.

### CODE REVIEW

**Comment by msplr** [comment]
How much should be checked by the bootloader?
Should there be a size limit?

**Comment by antoinealb** [comment]
I don't know. Is there any way to break stuff by reading an invalid adress ?

**Comment by antoinealb** [comment]
Also, I think we should use MessagePack's binary type instead of strings, as done in the write flash command.

**Comment by msplr** [comment]
> we should use MessagePack's binary type instead of strings

will change.

> Is there any way to break stuff by reading an invalid adress ?

No, it will cause a fault with a reboot.

**Comment by antoinealb** [comment]
Is a fault with a reboot a big problem ? I don't think it is, but maybe I am wrong.

**Pull request merged**
