### PR TITLE
CAN datagram receive class for client

### PR DESCRIPTION
**Pull request by msplr**
For testing I needed some code for receiving.

### CODE REVIEW

**Comment by antoinealb** [comment]
I will take a look when I get back from holidays but apparently the tests
fail on the CI build. Can you fix this ?

**Comment by msplr** [comment]
Oh, thanks for the remark.
Strange, it worked on my system... I'll try to fix it.

**Comment by antoinealb** [comment]
You are probably using deprecated or recent features. Normally the build
output will show the version.

**Comment by msplr** [comment]
Thanks, you were right. I used a too recent `struct.iter_unpack()` method. it works now.

**Comment by antoinealb** [comment]
So I read the code, and I am not a huge fan of having a class and a state machine for protocol decoding... It doesn't look very "pythonic" to me. Maybe we can use the struct module to do all the parsing ? I can try to write a proposal implementation if you want.

**Comment by msplr** [comment]
Agree.

**Pull request closed without merging**
