### PR TITLE
Flash writer proposal

### PR DESCRIPTION
**Pull request by msplr**
I added a header for a fash_writer, to discuss the API.
I made an [implementation](https://github.com/nuft/nucleo-f302-basic-example/tree/flash-writer-test) for the STM32F3.
We should also discuss how much the master is aware about the flash layout of the MCU. 
(all F3's have 2K pages, other controllers, like the F4, have pages of different sizes.)

### CODE REVIEW

**Comment by antoinealb** [comment]
I think the master should not know the flash layout. Only the upload script running on the PC would know it in my opinion.

**Comment by msplr** [comment]
Right, I wasn't precise. I meant the upload script on the PC as the master.
The master board should only relay the commands coming from the script.

**Comment by antoinealb** [comment]
When we discussed it briefly with @Stapelzeiger, we thought that the maximum datagram size should be adjusted to be the size of a flash page + protocol overhead. The main reason for this being that we cannot put 16k datagrams everywhere, because of RAM limitations. So at least the flash page is needed.

Did you have any other flash layout informations in mind ?

**Comment by antoinealb** [comment]
For your API, I don't know if `flash_writer_word_write` is useful. We will probably be writing a whole page at a time. Also, I don't know if the page erase function is useful. I would prefer a single function call "simply write this bunch of data to the page starting at this adress" and not handle all the details. The page size function is useful though.

**Comment by msplr** [comment]
> we thought that the maximum datagram size should be adjusted to be the size of a flash page + protocol overhead

ok, but MCUs like the F4 have up to 128K pages. It has enough continuous RAM to hold a page, but it's still lot for one datagram.

**Comment by antoinealb** [comment]
What is the page size of our MCU ?

**Comment by msplr** [comment]
And since I'm looking at datagram size: `data_len` in `can_datagram_t` is a `uint16_t` which means max 64K per datagram.

> What is the page size of our MCU ?

for STM32F3's: all pages are 2K
But on the master card is an STM32F4.

**Comment by antoinealb** [comment]
The master is designed to be programmed using onboard black magic probe. I'd say we don't change the design for the master and if we realize the probe does not work (unlikely but who knows) we will find something.

**Pull request merged**
