### PR TITLE
Flash writer stm32f3

### PR DESCRIPTION
**Pull request by msplr**
Finally some code for the f3. I also added the libopencm3 library as submodule.

### CODE REVIEW

**Comment by antoinealb** [comment]
Was it tested on hardware ?

**Comment by msplr** [comment]
Yes, I tested it on the f3 nucleo board.

**Comment by msplr** [comment]
We could still discuss if the granularity of 1 byte in `flash_writer_page_write()` is really needed.

**Comment by antoinealb** [comment]
Is there any downside to have this granularity ?

**Comment by msplr** [comment]
No, but I think that we don't need it.
We can leave it like that.

**Comment by antoinealb** [comment]
Let's leave it like this for the moment, it prevent any bad surprises.

**Pull request merged**
