### PR TITLE
Boot code, config update, read flash...

### PR DESCRIPTION
**Pull request by msplr**
My progress so far.
I'm sure these changes break some unit tests, thought I think it's more important to first get the code together in one place.
I'm testing the bootloader as a package in this repo https://github.com/nuft/servo-board-v1-bootloader

### CODE REVIEW

**Comment by antoinealb** [comment]
In the end do we want the repository to have the whole application or be a package for something else ? I would prefer to have the whole bootloader in one place personally.

**Comment by msplr** [comment]
I'm against, because we also want to run the bootloader on other controllers.
(The motor boards will not always be the only boards on the CAN bus)
This means there will be board specific startup code/linker scripts/etc., which we don't want all in one place.
And it would be nice to add some LED status indication to the bootloader.

**Comment by Stapelzeiger** [comment]
I guess the changes will be minimal. We could use different branches for the various targets.
Two repositories are ok too.

**Comment by antoinealb** [comment]
In term of Travis CI, I don't know which one is the best.

**Comment by antoinealb** [comment]
Merging it for now, we can discuss repository organization later.

**Pull request merged**
