### PR TITLE
Use external python implementation

### PR DESCRIPTION
**Pull request by antoinealb**
This can only work once cvra/serial-can-bridge#2 gets merged. It replaces the built in can bridge implementation and implements a CAN ID filter.

Still a WIP though.

### CODE REVIEW

**Comment by msplr** [comment]
How do I add the can bridge module?
Without it I can't test the client.

**Comment by antoinealb** [comment]
this should work:

``` bash
cd /path/to/serial-can-bridge/python
python setup.py install
```

Note: This will install it system-wide.

**Comment by msplr** [comment]
> Note: This will install it system-wide.

Any way to avoid this?

**Comment by antoinealb** [comment]
Use virtual environments: http://docs.python-guide.org/en/latest/dev/virtualenvs/

It is very easy to use (just need a tutorial) and it is the best way to handle development dependencies in my opinion.

**Comment by antoinealb** [comment]
I will have to add it to travis too.

**Comment by antoinealb** [comment]
You can also uninstall the package via pip: `pip uninstall serial_can_bridge`.

**Comment by antoinealb** [comment]
So I tested it on hardware this afternoon, it works.

**Pull request merged**
